-- Auto-generated by scripts/seed/generate-sql.ts
-- Do not edit manually. Re-run the generator after scraping.
-- Generated at: 2026-04-15T06:04:30.085Z

-- ── Nike brand ──────────────────────────────────────────

INSERT INTO brands (id, name, enabled, region)
VALUES ('19abb8da-e2b5-57ab-ae0d-a4c85460bdbc', 'Nike', true, 'NA')
ON CONFLICT (name) DO UPDATE SET enabled = EXCLUDED.enabled, region = EXCLUDED.region;

-- ── mens / shoes ──

INSERT INTO brand_size_charts (id, brand_id, gender_category, product_category)
VALUES ('34233af3-f23a-5c72-a853-d63769a7e005', '19abb8da-e2b5-57ab-ae0d-a4c85460bdbc', 'mens', 'shoes')
ON CONFLICT (brand_id, gender_category, product_category) DO NOTHING;

INSERT INTO brand_size_chart_entries (id, size_chart_id, size_label, measurement_ranges)
VALUES
  ('a7481bfc-81a3-5fa2-9303-8173717e8796', '34233af3-f23a-5c72-a853-d63769a7e005', 'US M3.5', '{"foot_length_cm":[22.5,22.5]}'),
  ('1795e39b-dd19-5bb2-a574-127b65f86b1d', '34233af3-f23a-5c72-a853-d63769a7e005', 'US M4', '{"foot_length_cm":[23,23]}'),
  ('a88536d9-2231-50e1-8f5a-aa5dc72012e0', '34233af3-f23a-5c72-a853-d63769a7e005', 'US M4.5', '{"foot_length_cm":[23.5,23.5]}'),
  ('9e6c0dd4-5d6e-5932-838f-a8acc618773f', '34233af3-f23a-5c72-a853-d63769a7e005', 'US M5', '{"foot_length_cm":[23.5,23.5]}'),
  ('49ff66c4-b25a-5581-9ca8-f95ba8363a5f', '34233af3-f23a-5c72-a853-d63769a7e005', 'US M5.5', '{"foot_length_cm":[24,24]}'),
  ('5e9083a6-70a6-523b-882c-ade586063b26', '34233af3-f23a-5c72-a853-d63769a7e005', 'US M6', '{"foot_length_cm":[24,24]}'),
  ('13379ebd-5105-57cf-a53f-04df2afa24fd', '34233af3-f23a-5c72-a853-d63769a7e005', 'US M6.5', '{"foot_length_cm":[24.5,24.5]}'),
  ('e569b143-f56d-59b8-977b-5d82b7f8bc98', '34233af3-f23a-5c72-a853-d63769a7e005', 'US M7', '{"foot_length_cm":[25,25]}'),
  ('1d803d13-9173-5a78-bb83-db485ba71df2', '34233af3-f23a-5c72-a853-d63769a7e005', 'US M7.5', '{"foot_length_cm":[25.5,25.5]}'),
  ('b9b48608-3795-57b3-980a-d90df7f7e7c9', '34233af3-f23a-5c72-a853-d63769a7e005', 'US M8', '{"foot_length_cm":[26,26]}'),
  ('2525a84c-c2c7-5522-88de-15e7aac02285', '34233af3-f23a-5c72-a853-d63769a7e005', 'US M8.5', '{"foot_length_cm":[26.5,26.5]}'),
  ('0b209372-25b7-5603-9bcc-b1df769d19d7', '34233af3-f23a-5c72-a853-d63769a7e005', 'US M9', '{"foot_length_cm":[27,27]}'),
  ('610f83a4-7ee2-5a21-9abe-2cf40821cfd4', '34233af3-f23a-5c72-a853-d63769a7e005', 'US M9.5', '{"foot_length_cm":[27.5,27.5]}'),
  ('5c3eef89-7b25-545a-a849-2d129b8eae2a', '34233af3-f23a-5c72-a853-d63769a7e005', 'US M10', '{"foot_length_cm":[28,28]}'),
  ('31ea640c-a919-5ce5-81ce-4b9976d453b6', '34233af3-f23a-5c72-a853-d63769a7e005', 'US M10.5', '{"foot_length_cm":[28.5,28.5]}'),
  ('ba87296e-9a62-5ce8-81e8-25cf46912412', '34233af3-f23a-5c72-a853-d63769a7e005', 'US M11', '{"foot_length_cm":[29,29]}'),
  ('5cee47a9-9c4c-5347-a7ad-6e19bebbe280', '34233af3-f23a-5c72-a853-d63769a7e005', 'US M11.5', '{"foot_length_cm":[29.5,29.5]}'),
  ('4e10ab94-e16b-5d18-a23d-b07540f3716c', '34233af3-f23a-5c72-a853-d63769a7e005', 'US M12', '{"foot_length_cm":[30,30]}'),
  ('3899b72f-25e3-5ae0-8d71-57c91ef11401', '34233af3-f23a-5c72-a853-d63769a7e005', 'US M12.5', '{"foot_length_cm":[30.5,30.5]}'),
  ('fe14c400-e6bc-5ef0-80c3-f96bfd3f52a4', '34233af3-f23a-5c72-a853-d63769a7e005', 'US M13', '{"foot_length_cm":[31,31]}'),
  ('cbf2cccd-e56d-5a57-90ac-9536c962b043', '34233af3-f23a-5c72-a853-d63769a7e005', 'US M13.5', '{"foot_length_cm":[31.5,31.5]}'),
  ('16ac5fdd-81c2-5338-9d33-182b113424be', '34233af3-f23a-5c72-a853-d63769a7e005', 'US M14', '{"foot_length_cm":[32,32]}'),
  ('bc449145-67ea-5823-b4b2-a90a4bf45c48', '34233af3-f23a-5c72-a853-d63769a7e005', 'US M14.5', '{"foot_length_cm":[32.5,32.5]}'),
  ('9df32399-a56a-5378-920c-c027024e3a19', '34233af3-f23a-5c72-a853-d63769a7e005', 'US M15', '{"foot_length_cm":[33,33]}'),
  ('5c906786-b253-5199-957b-6981bd2b6e2c', '34233af3-f23a-5c72-a853-d63769a7e005', 'US M15.5', '{"foot_length_cm":[33.5,33.5]}'),
  ('395083c7-5ecb-5f40-b7ff-c5e85f39db19', '34233af3-f23a-5c72-a853-d63769a7e005', 'US M16', '{"foot_length_cm":[34,34]}'),
  ('8bb7be62-5291-58bb-b0f0-db92ee2a1593', '34233af3-f23a-5c72-a853-d63769a7e005', 'US M16.5', '{"foot_length_cm":[34.5,34.5]}'),
  ('5f0b87f3-ee60-587b-82ff-ba5c086c701a', '34233af3-f23a-5c72-a853-d63769a7e005', 'US M17', '{"foot_length_cm":[35,35]}'),
  ('863c4b26-1d40-5f51-b213-a8d1c6e85b86', '34233af3-f23a-5c72-a853-d63769a7e005', 'US M17.5', '{"foot_length_cm":[35.5,35.5]}'),
  ('abd8f6eb-57ca-5bcc-ad3e-f3e04158a872', '34233af3-f23a-5c72-a853-d63769a7e005', 'US M18', '{"foot_length_cm":[36,36]}'),
  ('1515c98e-c566-5a7f-9e19-0f6e971a4034', '34233af3-f23a-5c72-a853-d63769a7e005', 'US M18.5', '{"foot_length_cm":[36.5,36.5]}'),
  ('90249278-4ff0-50b6-8d7b-9741f04dc6b0', '34233af3-f23a-5c72-a853-d63769a7e005', 'US M19', '{"foot_length_cm":[37,37]}'),
  ('3e97822a-7b03-53d3-9e81-43e70494ef7a', '34233af3-f23a-5c72-a853-d63769a7e005', 'US M19.5', '{"foot_length_cm":[37.5,37.5]}'),
  ('acc34da0-9ad4-5f06-a1d2-136a1542792b', '34233af3-f23a-5c72-a853-d63769a7e005', 'US M20', '{"foot_length_cm":[38,38]}'),
  ('40ad014a-8ad2-574a-9e5b-da09dc5d112c', '34233af3-f23a-5c72-a853-d63769a7e005', 'US M20.5', '{"foot_length_cm":[38.5,38.5]}'),
  ('55863b8a-f6bd-51f9-bd85-c2ec470ba469', '34233af3-f23a-5c72-a853-d63769a7e005', 'US M21', '{"foot_length_cm":[39,39]}'),
  ('b1e9ba17-1f9b-5570-b280-805a60726d87', '34233af3-f23a-5c72-a853-d63769a7e005', 'US M21.5', '{"foot_length_cm":[39.5,39.5]}'),
  ('65ff5477-fa26-5dfd-b24a-234f9e9f47c6', '34233af3-f23a-5c72-a853-d63769a7e005', 'US M22', '{"foot_length_cm":[40,40]}')
ON CONFLICT (size_chart_id, size_label) DO UPDATE SET
  measurement_ranges = EXCLUDED.measurement_ranges,
  updated_at = now();

-- ── mens / tops ──

INSERT INTO brand_size_charts (id, brand_id, gender_category, product_category)
VALUES ('49f4db60-780b-552e-9187-6b2a501d0110', '19abb8da-e2b5-57ab-ae0d-a4c85460bdbc', 'mens', 'tops')
ON CONFLICT (brand_id, gender_category, product_category) DO NOTHING;

INSERT INTO brand_size_chart_entries (id, size_chart_id, size_label, measurement_ranges)
VALUES
  ('8e6b8525-5f3b-5fff-ba8d-1c5b895c14ce', '49f4db60-780b-552e-9187-6b2a501d0110', 'XXS', '{"chest_cm":[71.4,80],"waist_cm":[57.2,64.8],"hip_cm":[72.4,80]}'),
  ('92997119-f70e-551b-88ac-d94d7835abaa', '49f4db60-780b-552e-9187-6b2a501d0110', 'XS', '{"chest_cm":[80,88.9],"waist_cm":[64.8,73.7],"hip_cm":[80,88.9]}'),
  ('99ba931d-a206-5d62-ae9c-17af701334ee', '49f4db60-780b-552e-9187-6b2a501d0110', 'S', '{"chest_cm":[88.9,95.3],"waist_cm":[73.7,81.3],"hip_cm":[88.9,95.3]}'),
  ('339ae8f5-87b2-5fe2-a999-d62573505671', '49f4db60-780b-552e-9187-6b2a501d0110', 'S Tall', '{"chest_cm":[88.9,95.3],"waist_cm":[73.7,81.3],"hip_cm":[88.9,95.3]}'),
  ('c9304291-7a4b-59d3-b9b1-8dd012d81c25', '49f4db60-780b-552e-9187-6b2a501d0110', 'M', '{"chest_cm":[95.3,104.1],"waist_cm":[81.3,88.9],"hip_cm":[95.3,104.1]}'),
  ('88fc0bd3-e881-53f8-943b-670e765269e1', '49f4db60-780b-552e-9187-6b2a501d0110', 'M Tall', '{"chest_cm":[95.3,104.1],"waist_cm":[81.3,88.9],"hip_cm":[95.3,104.1]}'),
  ('c3e4ac55-bccb-5e49-9633-986d4f80dc99', '49f4db60-780b-552e-9187-6b2a501d0110', 'L', '{"chest_cm":[104.1,111.8],"waist_cm":[88.9,96.5],"hip_cm":[104.1,111.8]}'),
  ('e3408cfc-a22a-534c-8d84-f48f6db9d818', '49f4db60-780b-552e-9187-6b2a501d0110', 'L Tall', '{"chest_cm":[104.1,111.8],"waist_cm":[88.9,96.5],"hip_cm":[104.1,111.8]}'),
  ('20bc45e3-eec2-5972-82f4-0171657bfef6', '49f4db60-780b-552e-9187-6b2a501d0110', 'XL', '{"chest_cm":[111.8,123.2],"waist_cm":[96.5,109.2],"hip_cm":[111.8,119.4]}'),
  ('8e8d3706-40cd-506f-ba30-4628c76be0ba', '49f4db60-780b-552e-9187-6b2a501d0110', 'XL Tall', '{"chest_cm":[111.8,123.2],"waist_cm":[96.5,109.2],"hip_cm":[111.8,119.4]}'),
  ('87b7c099-ba70-5a3c-8d59-9a44f98652ea', '49f4db60-780b-552e-9187-6b2a501d0110', 'XXL', '{"chest_cm":[123.2,135.9],"waist_cm":[109.2,120.7],"hip_cm":[119.4,128.3]}'),
  ('19e337d9-2eeb-5051-bba4-364fad6bed79', '49f4db60-780b-552e-9187-6b2a501d0110', 'XXL Tall', '{"chest_cm":[123.2,135.9],"waist_cm":[109.2,120.7],"hip_cm":[119.4,128.3]}'),
  ('4661ad27-0724-5318-aa21-7f04277e7088', '49f4db60-780b-552e-9187-6b2a501d0110', '3XL', '{"chest_cm":[135.9,147.3],"waist_cm":[120.7,133.4],"hip_cm":[128.3,135.9]}'),
  ('d530262b-18fa-5189-8a08-d392dfde1974', '49f4db60-780b-552e-9187-6b2a501d0110', '3XL Tall', '{"chest_cm":[135.9,147.3],"waist_cm":[120.7,133.4],"hip_cm":[128.3,135.9]}'),
  ('4ca270f9-28b8-503e-a96c-e073a0b6487b', '49f4db60-780b-552e-9187-6b2a501d0110', '4XL', '{"chest_cm":[147.3,160],"waist_cm":[133.4,144.8],"hip_cm":[135.9,148.6]}'),
  ('0321d509-594d-5002-afc8-d506a01d70f9', '49f4db60-780b-552e-9187-6b2a501d0110', '4XL Tall', '{"chest_cm":[147.3,160],"waist_cm":[133.4,144.8],"hip_cm":[135.9,148.6]}'),
  ('5c6f68a0-4075-52f0-a379-158282f14848', '49f4db60-780b-552e-9187-6b2a501d0110', 'NBA XS', '{"chest_cm":[82.6,88.9],"waist_cm":[66,73.7],"hip_cm":[80,88.9]}'),
  ('d9e35f42-0f31-5d08-966e-01ce5a9691a6', '49f4db60-780b-552e-9187-6b2a501d0110', 'NBA S', '{"chest_cm":[88.9,95.3],"waist_cm":[73.7,81.3],"hip_cm":[88.9,95.3]}'),
  ('32f0e205-dde2-54c9-a3ce-6f5ae263ebc4', '49f4db60-780b-552e-9187-6b2a501d0110', 'NBA M', '{"chest_cm":[95.3,104.1],"waist_cm":[81.3,88.9],"hip_cm":[95.3,104.1]}'),
  ('c5805bff-fabf-5cf6-a180-bb1f8064e58f', '49f4db60-780b-552e-9187-6b2a501d0110', 'NBA L', '{"chest_cm":[104.1,111.8],"waist_cm":[88.9,96.5],"hip_cm":[104.1,111.8]}'),
  ('f12f294b-3392-5d50-9d40-912fe5b33869', '49f4db60-780b-552e-9187-6b2a501d0110', 'NBA XL', '{"chest_cm":[111.8,123.2],"waist_cm":[96.5,109.2],"hip_cm":[111.8,119.4]}'),
  ('2786322b-3b80-5e60-a77a-32e67c850811', '49f4db60-780b-552e-9187-6b2a501d0110', 'NBA XXL', '{"chest_cm":[123.2,135.9],"waist_cm":[109.2,120.7],"hip_cm":[119.4,128.3]}'),
  ('895171eb-59b2-547c-8a67-f7410938a8eb', '49f4db60-780b-552e-9187-6b2a501d0110', 'NBA 3XL', '{"chest_cm":[135.9,147.3],"waist_cm":[120.7,133.4],"hip_cm":[128.3,135.9]}')
ON CONFLICT (size_chart_id, size_label) DO UPDATE SET
  measurement_ranges = EXCLUDED.measurement_ranges,
  updated_at = now();

-- ── mens / bottoms ──

INSERT INTO brand_size_charts (id, brand_id, gender_category, product_category)
VALUES ('f72ad5b3-7335-510c-a93c-a80fa455afad', '19abb8da-e2b5-57ab-ae0d-a4c85460bdbc', 'mens', 'bottoms')
ON CONFLICT (brand_id, gender_category, product_category) DO NOTHING;

INSERT INTO brand_size_chart_entries (id, size_chart_id, size_label, measurement_ranges)
VALUES
  ('465c3e44-76f3-54e5-9fd4-7b26625d334d', 'f72ad5b3-7335-510c-a93c-a80fa455afad', 'XXS', '{"waist_cm":[57.2,64.8],"hip_cm":[72.4,80]}'),
  ('1a4cfd6b-8964-5a60-876c-3a6174c8a731', 'f72ad5b3-7335-510c-a93c-a80fa455afad', 'XS', '{"waist_cm":[64.8,73.7],"hip_cm":[80,88.9]}'),
  ('2c9af24a-bfdb-5106-a148-1068d014236b', 'f72ad5b3-7335-510c-a93c-a80fa455afad', 'S', '{"waist_cm":[73.7,81.3],"hip_cm":[88.9,95.3]}'),
  ('1d4b99c3-ef2a-567a-ba5f-72c69b355f2a', 'f72ad5b3-7335-510c-a93c-a80fa455afad', 'S Tall', '{"waist_cm":[73.7,81.3],"hip_cm":[88.9,95.3]}'),
  ('5c83aa91-fce7-5e04-94e8-56e47d5f02f7', 'f72ad5b3-7335-510c-a93c-a80fa455afad', 'M', '{"waist_cm":[81.3,88.9],"hip_cm":[95.3,104.1]}'),
  ('017b9dcb-289e-591f-995a-d654f95a2bca', 'f72ad5b3-7335-510c-a93c-a80fa455afad', 'M Tall', '{"waist_cm":[81.3,88.9],"hip_cm":[95.3,104.1]}'),
  ('dd359ef8-06f6-5b9e-9cec-a7e85a1661c7', 'f72ad5b3-7335-510c-a93c-a80fa455afad', 'L', '{"waist_cm":[88.9,96.5],"hip_cm":[104.1,111.8]}'),
  ('c763b73c-a9c1-5d2c-a1da-2e8c486411af', 'f72ad5b3-7335-510c-a93c-a80fa455afad', 'L Tall', '{"waist_cm":[88.9,96.5],"hip_cm":[104.1,111.8]}'),
  ('f8257219-6727-5f30-b100-ec95b100659b', 'f72ad5b3-7335-510c-a93c-a80fa455afad', 'XL', '{"waist_cm":[96.5,109.2],"hip_cm":[111.8,119.4]}'),
  ('283f5c0c-8fb4-57d2-add3-6ca6b97c6a4d', 'f72ad5b3-7335-510c-a93c-a80fa455afad', 'XL Tall', '{"waist_cm":[96.5,109.2],"hip_cm":[111.8,119.4]}'),
  ('7e0979ac-368d-50cb-b8a0-c69e8e713bb5', 'f72ad5b3-7335-510c-a93c-a80fa455afad', 'XXL', '{"waist_cm":[109.2,120.7],"hip_cm":[119.4,128.3]}'),
  ('07200c0d-7d1f-5ae7-ac82-07d13488432a', 'f72ad5b3-7335-510c-a93c-a80fa455afad', 'XXL Tall', '{"waist_cm":[109.2,120.7],"hip_cm":[119.4,128.3]}'),
  ('dec59f14-c24a-5851-aa8f-c58807c5f4de', 'f72ad5b3-7335-510c-a93c-a80fa455afad', '3XL', '{"waist_cm":[120.7,133.4],"hip_cm":[128.3,135.9]}'),
  ('c4963153-f7c1-54c8-8810-78ed47962aee', 'f72ad5b3-7335-510c-a93c-a80fa455afad', '3XL Tall', '{"waist_cm":[120.7,133.4],"hip_cm":[128.3,135.9]}'),
  ('7ce305d5-d054-5bdb-92bd-cb5402202ccf', 'f72ad5b3-7335-510c-a93c-a80fa455afad', '4XL', '{"waist_cm":[133.4,144.8],"hip_cm":[135.9,148.6]}'),
  ('ad84bdc6-6458-5cbe-8216-27eb27a072d9', 'f72ad5b3-7335-510c-a93c-a80fa455afad', '4XL Tall', '{"waist_cm":[133.4,144.8],"hip_cm":[135.9,148.6]}'),
  ('381f1611-c1b0-5108-bf3e-fb904a8d571c', 'f72ad5b3-7335-510c-a93c-a80fa455afad', '26', '{"waist_cm":[69.9,69.9],"hip_cm":[85.1,85.1]}'),
  ('8e6c0334-0577-5076-9ea4-69f3f7ca570c', 'f72ad5b3-7335-510c-a93c-a80fa455afad', '28', '{"waist_cm":[74.9,74.9],"hip_cm":[90.2,90.2]}'),
  ('e0726c78-ccd4-502c-adf1-ea5bce134c9c', 'f72ad5b3-7335-510c-a93c-a80fa455afad', '30', '{"waist_cm":[80,80],"hip_cm":[95.3,95.3]}'),
  ('2eb95e08-6634-5861-a7e5-bf4b06a6d364', 'f72ad5b3-7335-510c-a93c-a80fa455afad', '32', '{"waist_cm":[85.1,85.1],"hip_cm":[100.3,100.3]}'),
  ('427b3d7e-88f1-5b29-9757-b885456ff1c9', 'f72ad5b3-7335-510c-a93c-a80fa455afad', '34', '{"waist_cm":[90.2,90.2],"hip_cm":[105.4,105.4]}'),
  ('f441ada9-1019-52cd-ba47-2f5094884eb4', 'f72ad5b3-7335-510c-a93c-a80fa455afad', '35', '{"waist_cm":[92.7,92.7],"hip_cm":[108,108]}'),
  ('11dd0596-9d33-56ac-a718-470d0f7bcb07', 'f72ad5b3-7335-510c-a93c-a80fa455afad', '36', '{"waist_cm":[95.3,95.3],"hip_cm":[110.5,110.5]}'),
  ('597cb23e-9f94-55b9-aba0-f37f5b26f5f2', 'f72ad5b3-7335-510c-a93c-a80fa455afad', '37', '{"waist_cm":[97.8,97.8],"hip_cm":[113,113]}'),
  ('e987d8b7-0637-526c-95a0-3ca8948f811d', 'f72ad5b3-7335-510c-a93c-a80fa455afad', '38', '{"waist_cm":[100.3,100.3],"hip_cm":[115.6,115.6]}'),
  ('e63b96e7-ca13-50be-a48c-7bbc51eb46be', 'f72ad5b3-7335-510c-a93c-a80fa455afad', '40', '{"waist_cm":[105.4,105.4],"hip_cm":[120.7,120.7]}'),
  ('6b056e7c-d85c-527d-8b06-832603eae084', 'f72ad5b3-7335-510c-a93c-a80fa455afad', '42', '{"waist_cm":[110.5,110.5],"hip_cm":[125.7,125.7]}'),
  ('dfe46672-5c6e-5b52-8b9b-24669ef34236', 'f72ad5b3-7335-510c-a93c-a80fa455afad', '44', '{"waist_cm":[115.6,115.6],"hip_cm":[130.8,130.8]}'),
  ('915a84aa-a266-5595-b55c-034ccba10a20', 'f72ad5b3-7335-510c-a93c-a80fa455afad', '46', '{"waist_cm":[120.7,120.7],"hip_cm":[135.9,135.9]}'),
  ('c3433a4f-03a3-581c-a5f5-180db8dab5e0', 'f72ad5b3-7335-510c-a93c-a80fa455afad', '48', '{"waist_cm":[125.7,125.7],"hip_cm":[141,141]}'),
  ('09f7c8ae-0ca3-54a3-b2c9-ed5c21ec6cfa', 'f72ad5b3-7335-510c-a93c-a80fa455afad', 'NBA S', '{"waist_cm":[73.7,81.3],"hip_cm":[88.9,95.3]}'),
  ('cd7eca2b-60f3-5cfe-8222-b55690e25f0c', 'f72ad5b3-7335-510c-a93c-a80fa455afad', 'NBA M', '{"waist_cm":[81.3,88.9],"hip_cm":[95.3,104.1]}'),
  ('7fe83b19-8efb-51e7-ab7b-d987338f0451', 'f72ad5b3-7335-510c-a93c-a80fa455afad', 'NBA L', '{"waist_cm":[88.9,96.5],"hip_cm":[104.1,111.8]}'),
  ('05f3b3b1-a2ab-58c4-ba9a-b60fc0347d90', 'f72ad5b3-7335-510c-a93c-a80fa455afad', 'NBA XL', '{"waist_cm":[96.5,109.2],"hip_cm":[111.8,119.4]}'),
  ('b40695ba-b7de-53ae-b7df-8c206318af61', 'f72ad5b3-7335-510c-a93c-a80fa455afad', 'NBA 2XL', '{"waist_cm":[109.2,120.7],"hip_cm":[119.4,128.3]}'),
  ('9318ecd5-aee9-5639-8765-2ebaf0e7fa58', 'f72ad5b3-7335-510c-a93c-a80fa455afad', 'NBA 3XL', '{"waist_cm":[120.7,133.4],"hip_cm":[128.3,135.9]}'),
  ('6aba3d92-8700-58f5-b537-2c99b5cb2836', 'f72ad5b3-7335-510c-a93c-a80fa455afad', 'Swim XS', '{"chest_cm":[82.6,90.2],"waist_cm":[66,73.7],"hip_cm":[81.3,88.9]}'),
  ('fdee735a-7d3e-528a-81e9-2dc009e29ce7', 'f72ad5b3-7335-510c-a93c-a80fa455afad', 'Swim S', '{"chest_cm":[90.2,97.8],"waist_cm":[73.7,81.3],"hip_cm":[88.9,96.5]}'),
  ('d18f8bb9-8574-5a9b-9a13-042d65451fdf', 'f72ad5b3-7335-510c-a93c-a80fa455afad', 'Swim M', '{"chest_cm":[97.8,105.4],"waist_cm":[81.3,88.9],"hip_cm":[96.5,104.1]}'),
  ('7db3d61d-e367-5954-a4e5-aadc06cb7e87', 'f72ad5b3-7335-510c-a93c-a80fa455afad', 'Swim L', '{"chest_cm":[105.4,113],"waist_cm":[88.9,96.5],"hip_cm":[104.1,111.8]}'),
  ('5532acea-d3ef-5291-b937-6c9c2c104134', 'f72ad5b3-7335-510c-a93c-a80fa455afad', 'Swim XL', '{"chest_cm":[113,120.7],"waist_cm":[96.5,104.1],"hip_cm":[111.8,119.4]}'),
  ('8ead133a-32db-5c61-ae1b-a8cf6178d41b', 'f72ad5b3-7335-510c-a93c-a80fa455afad', 'Swim XXL', '{"chest_cm":[120.7,129.5],"waist_cm":[104.1,111.8],"hip_cm":[119.4,127]}'),
  ('33cda60f-0b14-5395-8cf9-9befd42600c0', 'f72ad5b3-7335-510c-a93c-a80fa455afad', 'Swim 3XL', '{"chest_cm":[129.5,137.2],"waist_cm":[111.8,119.4],"hip_cm":[127,134.6]}'),
  ('3d1325b1-aa76-529d-9cf1-171f78f284c5', 'f72ad5b3-7335-510c-a93c-a80fa455afad', 'Swim 4XL', '{"chest_cm":[137.2,144.8],"waist_cm":[119.4,127],"hip_cm":[134.6,139.7]}'),
  ('f18044e1-6499-5eaf-aae3-6d377666ae6d', 'f72ad5b3-7335-510c-a93c-a80fa455afad', 'Underwear XS', '{"chest_cm":[76.2,81.3],"waist_cm":[61,66]}'),
  ('76f84ef3-9419-53ef-aa79-df8083477773', 'f72ad5b3-7335-510c-a93c-a80fa455afad', 'Underwear S', '{"chest_cm":[86.4,91.4],"waist_cm":[71.1,76.2]}'),
  ('87ffd519-f790-57fa-9032-a17901ec977c', 'f72ad5b3-7335-510c-a93c-a80fa455afad', 'Underwear M', '{"chest_cm":[96.5,101.6],"waist_cm":[81.3,86.4]}'),
  ('3caadabf-ef6d-53ad-aa24-7b1cadd448b6', 'f72ad5b3-7335-510c-a93c-a80fa455afad', 'Underwear L', '{"chest_cm":[106.7,111.8],"waist_cm":[91.4,96.5]}'),
  ('bea89f43-9968-5f94-82b3-b147d396efb8', 'f72ad5b3-7335-510c-a93c-a80fa455afad', 'Underwear XL', '{"chest_cm":[116.8,121.9],"waist_cm":[101.6,106.7]}'),
  ('b2804b65-4d62-5915-ba94-b0be3515747b', 'f72ad5b3-7335-510c-a93c-a80fa455afad', 'Underwear XXL', '{"chest_cm":[127,132.1],"waist_cm":[111.8,116.8]}'),
  ('1f19e096-30b5-5977-bd3f-37f4362d0bf7', 'f72ad5b3-7335-510c-a93c-a80fa455afad', 'Underwear XXS', '{"waist_cm":[53.3,58.4],"hip_cm":[77.5,82.6]}')
ON CONFLICT (size_chart_id, size_label) DO UPDATE SET
  measurement_ranges = EXCLUDED.measurement_ranges,
  updated_at = now();

-- ── womens / shoes ──

INSERT INTO brand_size_charts (id, brand_id, gender_category, product_category)
VALUES ('93bd0254-a7a3-54e5-a529-a778940580a0', '19abb8da-e2b5-57ab-ae0d-a4c85460bdbc', 'womens', 'shoes')
ON CONFLICT (brand_id, gender_category, product_category) DO NOTHING;

INSERT INTO brand_size_chart_entries (id, size_chart_id, size_label, measurement_ranges)
VALUES
  ('1c556a87-1368-5285-a0eb-ce3f150ac156', '93bd0254-a7a3-54e5-a529-a778940580a0', 'US W3.5', '{"foot_length_cm":[21,21]}'),
  ('2ea3da6e-e6f0-59d8-ba73-eefb157b6624', '93bd0254-a7a3-54e5-a529-a778940580a0', 'US W4', '{"foot_length_cm":[21,21]}'),
  ('fa088638-2ffe-5c21-83a8-ff7774acbd6a', '93bd0254-a7a3-54e5-a529-a778940580a0', 'US W4.5', '{"foot_length_cm":[21.5,21.5]}'),
  ('7f7a11a9-4d53-550c-a3ea-b27924bfcecc', '93bd0254-a7a3-54e5-a529-a778940580a0', 'US W5', '{"foot_length_cm":[22,22]}'),
  ('b7e0f88d-0c7d-5c0e-9888-4486acd8d30b', '93bd0254-a7a3-54e5-a529-a778940580a0', 'US W5.5', '{"foot_length_cm":[22.5,22.5]}'),
  ('209a507d-afae-5da8-b392-24b89809e33d', '93bd0254-a7a3-54e5-a529-a778940580a0', 'US W6', '{"foot_length_cm":[23,23]}'),
  ('11047b56-ec4e-5b71-b482-99375ff19680', '93bd0254-a7a3-54e5-a529-a778940580a0', 'US W6.5', '{"foot_length_cm":[23.5,23.5]}'),
  ('ea78d8d4-9164-5cf2-a008-98bda2cd4fc9', '93bd0254-a7a3-54e5-a529-a778940580a0', 'US W7', '{"foot_length_cm":[24,24]}'),
  ('dfff611a-0544-55ab-b595-4038d9d8833b', '93bd0254-a7a3-54e5-a529-a778940580a0', 'US W7.5', '{"foot_length_cm":[24.5,24.5]}'),
  ('6163441d-5fc5-52f1-a60f-95096df15665', '93bd0254-a7a3-54e5-a529-a778940580a0', 'US W8', '{"foot_length_cm":[25,25]}'),
  ('06c0c99d-757d-51ba-9d39-81c76a1aeb7c', '93bd0254-a7a3-54e5-a529-a778940580a0', 'US W8.5', '{"foot_length_cm":[25.5,25.5]}'),
  ('4fb34971-991a-53ec-87ac-455bd26ca154', '93bd0254-a7a3-54e5-a529-a778940580a0', 'US W9', '{"foot_length_cm":[26,26]}'),
  ('9015661d-cce6-5083-b79f-768e0713981b', '93bd0254-a7a3-54e5-a529-a778940580a0', 'US W9.5', '{"foot_length_cm":[26.5,26.5]}'),
  ('7351741e-31e1-5d25-a8c8-1e104ba9c69a', '93bd0254-a7a3-54e5-a529-a778940580a0', 'US W10', '{"foot_length_cm":[27,27]}'),
  ('893f468f-77a0-53f3-ab2f-74e87008a088', '93bd0254-a7a3-54e5-a529-a778940580a0', 'US W10.5', '{"foot_length_cm":[27.5,27.5]}'),
  ('f682e3c1-3388-5ff9-a66d-f0c7b3a2383d', '93bd0254-a7a3-54e5-a529-a778940580a0', 'US W11', '{"foot_length_cm":[28,28]}'),
  ('07d8b999-1fd5-5f18-b3d4-5e4290d50741', '93bd0254-a7a3-54e5-a529-a778940580a0', 'US W11.5', '{"foot_length_cm":[28.5,28.5]}'),
  ('71e59b60-21be-5ad2-b2af-4f5e011c08a8', '93bd0254-a7a3-54e5-a529-a778940580a0', 'US W12', '{"foot_length_cm":[29,29]}'),
  ('8222336a-df07-5c2c-b54c-8811688a5378', '93bd0254-a7a3-54e5-a529-a778940580a0', 'US W12.5', '{"foot_length_cm":[29.5,29.5]}'),
  ('c38ef441-721b-54a6-ab86-6ba6d390f37b', '93bd0254-a7a3-54e5-a529-a778940580a0', 'US W13', '{"foot_length_cm":[30,30]}'),
  ('45ea9922-e2cb-5657-aa34-55ae346b35a5', '93bd0254-a7a3-54e5-a529-a778940580a0', 'US W13.5', '{"foot_length_cm":[30.5,30.5]}'),
  ('257f9b9f-34f7-5557-b091-e60cc64259a1', '93bd0254-a7a3-54e5-a529-a778940580a0', 'US W14', '{"foot_length_cm":[31,31]}'),
  ('433eaa97-cbf5-58a4-9c39-02727a6544a4', '93bd0254-a7a3-54e5-a529-a778940580a0', 'US W14.5', '{"foot_length_cm":[31.5,31.5]}'),
  ('05db0b4f-3df8-51a8-999f-dfda4ab71166', '93bd0254-a7a3-54e5-a529-a778940580a0', 'US W15', '{"foot_length_cm":[32,32]}'),
  ('adb8423d-f0f5-5ce3-942a-84216660389d', '93bd0254-a7a3-54e5-a529-a778940580a0', 'US W15.5', '{"foot_length_cm":[32.5,32.5]}'),
  ('417ac4fc-b509-5aba-87e8-fe113214b804', '93bd0254-a7a3-54e5-a529-a778940580a0', 'US W16', '{"foot_length_cm":[33,33]}'),
  ('6b64aa4a-aed6-5397-b954-1db02d869993', '93bd0254-a7a3-54e5-a529-a778940580a0', 'US W16.5', '{"foot_length_cm":[33.5,33.5]}'),
  ('445a93f4-b653-5bff-ad05-797f4b649b65', '93bd0254-a7a3-54e5-a529-a778940580a0', 'US W17', '{"foot_length_cm":[34,34]}'),
  ('f89b277f-f04f-5347-918c-20146fda765f', '93bd0254-a7a3-54e5-a529-a778940580a0', 'US W17.5', '{"foot_length_cm":[34.5,34.5]}'),
  ('b01ba0dc-4ee5-5f35-892b-bc7e7b3b654e', '93bd0254-a7a3-54e5-a529-a778940580a0', 'US W18', '{"foot_length_cm":[35,35]}'),
  ('5f95b0e8-db1f-5bce-ab50-3005c173ffcb', '93bd0254-a7a3-54e5-a529-a778940580a0', 'US W18.5', '{"foot_length_cm":[35.5,35.5]}'),
  ('7896983a-30ed-5336-9e58-ad32f53e9576', '93bd0254-a7a3-54e5-a529-a778940580a0', 'US W19', '{"foot_length_cm":[36,36]}'),
  ('d204544a-8be2-5f9e-b1fa-608460b03489', '93bd0254-a7a3-54e5-a529-a778940580a0', 'US W19.5', '{"foot_length_cm":[36.5,36.5]}'),
  ('966d95a6-5934-5231-afef-8dff8cfaa736', '93bd0254-a7a3-54e5-a529-a778940580a0', 'US W20', '{"foot_length_cm":[37,37]}'),
  ('ddd78618-d0d0-5dbd-bce1-8329383310ec', '93bd0254-a7a3-54e5-a529-a778940580a0', 'US W20.5', '{"foot_length_cm":[37.5,37.5]}'),
  ('36b2d325-2df0-56e0-aaa6-2e32c580f6a7', '93bd0254-a7a3-54e5-a529-a778940580a0', 'US W21', '{"foot_length_cm":[38,38]}'),
  ('28eb20e6-258d-5eeb-9f90-e022dc905d5e', '93bd0254-a7a3-54e5-a529-a778940580a0', 'US W21.5', '{"foot_length_cm":[38.5,38.5]}'),
  ('8a84ea9f-d39b-53d1-a2ea-f389085ec01d', '93bd0254-a7a3-54e5-a529-a778940580a0', 'US W22', '{"foot_length_cm":[39,39]}'),
  ('5699d7f7-e010-5e07-8419-a1b560276419', '93bd0254-a7a3-54e5-a529-a778940580a0', 'US W22.5', '{"foot_length_cm":[39.5,39.5]}')
ON CONFLICT (size_chart_id, size_label) DO UPDATE SET
  measurement_ranges = EXCLUDED.measurement_ranges,
  updated_at = now();

-- ── womens / tops ──

INSERT INTO brand_size_charts (id, brand_id, gender_category, product_category)
VALUES ('5d7269db-7bb7-5a0c-b258-219b455ad541', '19abb8da-e2b5-57ab-ae0d-a4c85460bdbc', 'womens', 'tops')
ON CONFLICT (brand_id, gender_category, product_category) DO NOTHING;

INSERT INTO brand_size_chart_entries (id, size_chart_id, size_label, measurement_ranges)
VALUES
  ('4eb5c5b6-24a0-5bd2-8776-4fd286591bbc', '5d7269db-7bb7-5a0c-b258-219b455ad541', 'XXS', '{"chest_cm":[69.9,74.9],"waist_cm":[54,59.7],"hip_cm":[77.5,83.8]}'),
  ('63454a0b-b688-5fa2-85c1-ea686513226f', '5d7269db-7bb7-5a0c-b258-219b455ad541', 'XS', '{"chest_cm":[74.9,82.6],"waist_cm":[59.7,66],"hip_cm":[83.8,90.2]}'),
  ('4ad64392-99c1-5c6a-a009-09bf96b8bb9d', '5d7269db-7bb7-5a0c-b258-219b455ad541', 'S', '{"chest_cm":[82.6,90.2],"waist_cm":[66,73.7],"hip_cm":[90.2,97.8]}'),
  ('a620ef32-3e33-5101-851c-423140810e26', '5d7269db-7bb7-5a0c-b258-219b455ad541', 'M', '{"chest_cm":[90.2,96.5],"waist_cm":[73.7,80],"hip_cm":[97.8,104.1]}'),
  ('390e2ae1-7d17-547e-b082-432fac04e692', '5d7269db-7bb7-5a0c-b258-219b455ad541', 'L', '{"chest_cm":[96.5,104.1],"waist_cm":[80,87.6],"hip_cm":[104.1,111.8]}'),
  ('da17765d-e9f8-5940-b9c3-9253b2625c91', '5d7269db-7bb7-5a0c-b258-219b455ad541', 'XL', '{"chest_cm":[104.1,113],"waist_cm":[87.6,97.8],"hip_cm":[111.8,119.4]}'),
  ('65f89fe1-879e-56f2-8ecc-a0d7e3f93451', '5d7269db-7bb7-5a0c-b258-219b455ad541', 'XXL', '{"chest_cm":[113,123.2],"waist_cm":[97.8,108],"hip_cm":[119.4,127]}'),
  ('93f0444c-35de-5337-83bd-fddc65d9a5e3', '5d7269db-7bb7-5a0c-b258-219b455ad541', '0X', '{"chest_cm":[111.8,119.4],"waist_cm":[101.6,109.2],"hip_cm":[121.9,129.5]}'),
  ('62a82c8a-918a-5aaa-a5cc-fda501902ae8', '5d7269db-7bb7-5a0c-b258-219b455ad541', '1X', '{"chest_cm":[119.4,125.7],"waist_cm":[109.2,115.6],"hip_cm":[129.5,137.2]}'),
  ('c80492ce-db5f-5760-894f-ac0337c0f809', '5d7269db-7bb7-5a0c-b258-219b455ad541', '2X', '{"chest_cm":[125.7,132.1],"waist_cm":[115.6,124.5],"hip_cm":[137.2,144.8]}'),
  ('3b1c3c67-75c1-5fb0-8660-51d3a2c9abd4', '5d7269db-7bb7-5a0c-b258-219b455ad541', '3X', '{"chest_cm":[132.1,139.7],"waist_cm":[124.5,134.6],"hip_cm":[144.8,154.9]}'),
  ('7b616366-4012-58a0-a933-8d01f965f461', '5d7269db-7bb7-5a0c-b258-219b455ad541', '4X', '{"chest_cm":[139.7,147.3],"waist_cm":[134.6,144.8],"hip_cm":[154.9,165.1]}')
ON CONFLICT (size_chart_id, size_label) DO UPDATE SET
  measurement_ranges = EXCLUDED.measurement_ranges,
  updated_at = now();

-- ── womens / bottoms ──

INSERT INTO brand_size_charts (id, brand_id, gender_category, product_category)
VALUES ('67ba9a1f-01c1-5a54-97f6-aeff54dada73', '19abb8da-e2b5-57ab-ae0d-a4c85460bdbc', 'womens', 'bottoms')
ON CONFLICT (brand_id, gender_category, product_category) DO NOTHING;

INSERT INTO brand_size_chart_entries (id, size_chart_id, size_label, measurement_ranges)
VALUES
  ('a2955445-127c-5c73-9a64-40a0c45242bc', '67ba9a1f-01c1-5a54-97f6-aeff54dada73', 'XXS', '{"waist_cm":[54,59.7],"hip_cm":[77.5,83.8]}'),
  ('7193c043-a180-5a1f-9fcc-33f1a3c36676', '67ba9a1f-01c1-5a54-97f6-aeff54dada73', 'XS', '{"waist_cm":[59.7,66],"hip_cm":[83.8,90.2]}'),
  ('bdaefbbc-45bd-5f0a-a493-959265d8f176', '67ba9a1f-01c1-5a54-97f6-aeff54dada73', 'S', '{"waist_cm":[66,73.7],"hip_cm":[90.2,97.8]}'),
  ('67168969-a045-5300-9399-98f8349e7623', '67ba9a1f-01c1-5a54-97f6-aeff54dada73', 'M', '{"waist_cm":[73.7,80],"hip_cm":[97.8,104.1]}'),
  ('4f5402af-df54-54ae-9d5c-fa77a09a40d9', '67ba9a1f-01c1-5a54-97f6-aeff54dada73', 'L', '{"waist_cm":[80,87.6],"hip_cm":[104.1,111.8]}'),
  ('479e9f21-f984-53aa-a019-56168035c4d9', '67ba9a1f-01c1-5a54-97f6-aeff54dada73', 'XL', '{"waist_cm":[87.6,97.8],"hip_cm":[111.8,119.4]}'),
  ('ac10e70f-a5cc-54a6-bcc7-4668ec264795', '67ba9a1f-01c1-5a54-97f6-aeff54dada73', 'XXL', '{"waist_cm":[97.8,108],"hip_cm":[119.4,127]}'),
  ('18641e3f-b5cc-5f07-82bf-5eb1ad356335', '67ba9a1f-01c1-5a54-97f6-aeff54dada73', '0X', '{"waist_cm":[101.6,109.2],"hip_cm":[121.9,129.5]}'),
  ('ffb82b34-d724-50df-9fa4-822d7e7d606b', '67ba9a1f-01c1-5a54-97f6-aeff54dada73', '1X', '{"waist_cm":[109.2,115.6],"hip_cm":[129.5,137.2]}'),
  ('9c9ee372-1f76-5a03-a7d0-302a17e759af', '67ba9a1f-01c1-5a54-97f6-aeff54dada73', '2X', '{"waist_cm":[115.6,124.5],"hip_cm":[137.2,144.8]}'),
  ('c3f0b4c2-687f-579a-beac-1f14b04e6252', '67ba9a1f-01c1-5a54-97f6-aeff54dada73', '3X', '{"waist_cm":[124.5,134.6],"hip_cm":[144.8,154.9]}'),
  ('dbb90abc-ff72-55d5-af98-ae8dc086c501', '67ba9a1f-01c1-5a54-97f6-aeff54dada73', '4X', '{"waist_cm":[134.6,144.8],"hip_cm":[154.9,165.1]}'),
  ('713ed889-ccaf-5d6b-88fd-7553010c30ba', '67ba9a1f-01c1-5a54-97f6-aeff54dada73', '0', '{"chest_cm":[74.9,74.9],"waist_cm":[58.4,58.4],"hip_cm":[82.6,82.6]}'),
  ('e115609e-3d0b-5b0c-b35a-a5214e0ebe75', '67ba9a1f-01c1-5a54-97f6-aeff54dada73', '2', '{"chest_cm":[78.7,78.7],"waist_cm":[62.2,62.2],"hip_cm":[86.4,86.4]}'),
  ('e52d6bd0-97e4-5f45-820a-84f70e2ff07e', '67ba9a1f-01c1-5a54-97f6-aeff54dada73', '4', '{"chest_cm":[82.6,82.6],"waist_cm":[66,66],"hip_cm":[90.2,90.2]}'),
  ('ab106bc0-3cbc-536c-8bac-11b84db8e1f0', '67ba9a1f-01c1-5a54-97f6-aeff54dada73', '6', '{"chest_cm":[86.4,86.4],"waist_cm":[69.9,69.9],"hip_cm":[94,94]}'),
  ('499c9f25-6d39-5d7f-85c0-f1772ba873eb', '67ba9a1f-01c1-5a54-97f6-aeff54dada73', '8', '{"chest_cm":[90.2,90.2],"waist_cm":[73.7,73.7],"hip_cm":[97.8,97.8]}'),
  ('b6750adf-5da4-584a-b422-822d157caf36', '67ba9a1f-01c1-5a54-97f6-aeff54dada73', '10', '{"chest_cm":[94,94],"waist_cm":[77.5,77.5],"hip_cm":[101.6,101.6]}'),
  ('68ec00c0-6359-5556-961d-2d7723d1999e', '67ba9a1f-01c1-5a54-97f6-aeff54dada73', '12', '{"chest_cm":[97.8,97.8],"waist_cm":[81.3,81.3],"hip_cm":[105.4,105.4]}'),
  ('0b0b9721-6e46-5704-a7de-83ae7389aa82', '67ba9a1f-01c1-5a54-97f6-aeff54dada73', '14', '{"chest_cm":[104.1,104.1],"waist_cm":[86.4,86.4],"hip_cm":[110.5,110.5]}'),
  ('2f0aecc2-3146-5c50-a16c-95c85d7a5f81', '67ba9a1f-01c1-5a54-97f6-aeff54dada73', '16', '{"chest_cm":[110.5,110.5],"waist_cm":[91.4,91.4],"hip_cm":[115.6,115.6]}'),
  ('12ed62a7-6310-505d-bb7d-f92fee1b59cb', '67ba9a1f-01c1-5a54-97f6-aeff54dada73', '18', '{"chest_cm":[116.8,116.8],"waist_cm":[96.5,96.5],"hip_cm":[120.7,120.7]}'),
  ('a1dde73b-7a9c-5e0c-9d70-0a87b255cba3', '67ba9a1f-01c1-5a54-97f6-aeff54dada73', '20', '{"chest_cm":[123.2,123.2],"waist_cm":[101.6,101.6],"hip_cm":[125.7,125.7]}'),
  ('1fba6fce-63c0-54d1-929d-4fec7dfd0e6b', '67ba9a1f-01c1-5a54-97f6-aeff54dada73', '22', '{"chest_cm":[129.5,129.5],"waist_cm":[106.7,106.7],"hip_cm":[130.8,130.8]}'),
  ('144728c7-e6d7-5b01-ba52-f2c1df68fbc4', '67ba9a1f-01c1-5a54-97f6-aeff54dada73', '16W', '{"waist_cm":[100.3,100.3],"hip_cm":[119.4,119.4]}'),
  ('381bf933-fd06-54a4-a9e5-e4500b4311d1', '67ba9a1f-01c1-5a54-97f6-aeff54dada73', '18W', '{"waist_cm":[105.4,105.4],"hip_cm":[124.5,124.5]}'),
  ('2bf7d174-93d5-557f-a2f2-c9158c8a97dd', '67ba9a1f-01c1-5a54-97f6-aeff54dada73', '20W', '{"waist_cm":[110.5,110.5],"hip_cm":[129.5,129.5]}'),
  ('cf291a8c-e4ed-59b1-8d6c-32904a76d3e7', '67ba9a1f-01c1-5a54-97f6-aeff54dada73', '22W', '{"waist_cm":[115.6,115.6],"hip_cm":[134.6,134.6]}'),
  ('c8ed46e5-84d9-5fe4-b0a7-66e137c122ea', '67ba9a1f-01c1-5a54-97f6-aeff54dada73', '24W', '{"waist_cm":[120.7,120.7],"hip_cm":[139.7,139.7]}'),
  ('f4d24524-0a44-5327-be47-910d2741a3bb', '67ba9a1f-01c1-5a54-97f6-aeff54dada73', '26W', '{"waist_cm":[125.7,125.7],"hip_cm":[144.8,144.8]}'),
  ('7e9f448c-eb88-59a0-adf3-fa6b64e7ac5c', '67ba9a1f-01c1-5a54-97f6-aeff54dada73', 'WNBA XS', '{"waist_cm":[59.7,66],"hip_cm":[83.8,90.2]}'),
  ('4857dbe4-55f9-5b35-aa51-f5201dd9a150', '67ba9a1f-01c1-5a54-97f6-aeff54dada73', 'WNBA S', '{"waist_cm":[66,73.7],"hip_cm":[90.2,97.8]}'),
  ('2e9ac0d7-8fc3-5571-bad1-ffb8f5a8d096', '67ba9a1f-01c1-5a54-97f6-aeff54dada73', 'WNBA M', '{"waist_cm":[73.7,80],"hip_cm":[97.8,104.1]}'),
  ('f39509de-c60a-59a2-a83a-2b67ec830a0c', '67ba9a1f-01c1-5a54-97f6-aeff54dada73', 'WNBA L', '{"waist_cm":[80,87.6],"hip_cm":[104.1,111.8]}'),
  ('529bc5ac-c53b-5354-ad08-17d1758dcd0f', '67ba9a1f-01c1-5a54-97f6-aeff54dada73', 'WNBA XL', '{"waist_cm":[87.6,97.8],"hip_cm":[111.8,119.4]}'),
  ('89c12a77-d247-5fc3-a16e-f1827c5952db', '67ba9a1f-01c1-5a54-97f6-aeff54dada73', 'WNBA 2XL', '{"waist_cm":[97.8,108],"hip_cm":[119.4,127]}'),
  ('5c405b20-ca39-5f81-bb7c-e8abbe97650c', '67ba9a1f-01c1-5a54-97f6-aeff54dada73', 'WNBA 3XL', '{"waist_cm":[108,118.1],"hip_cm":[127,135.9]}'),
  ('a98f3d89-494d-585d-9c48-0ffc7da596ae', '67ba9a1f-01c1-5a54-97f6-aeff54dada73', 'Skirt XXS', '{"chest_cm":[69.9,74.9],"waist_cm":[54,59.7],"hip_cm":[77.5,83.8]}'),
  ('99cb53ad-203e-558b-ae72-05d688f71b0d', '67ba9a1f-01c1-5a54-97f6-aeff54dada73', 'Skirt XS', '{"chest_cm":[74.9,82.6],"waist_cm":[59.7,66],"hip_cm":[83.8,90.2]}'),
  ('ee31eb00-da94-5a60-860a-27681aeb6aaf', '67ba9a1f-01c1-5a54-97f6-aeff54dada73', 'Skirt S', '{"chest_cm":[82.6,90.2],"waist_cm":[66,73.7],"hip_cm":[90.2,97.8]}'),
  ('30b60649-cc7d-5855-ae9d-f1b34f337e6b', '67ba9a1f-01c1-5a54-97f6-aeff54dada73', 'Skirt M', '{"chest_cm":[90.2,96.5],"waist_cm":[73.7,80],"hip_cm":[97.8,104.1]}'),
  ('29c85997-24f8-5759-9033-8aee1ca1f75a', '67ba9a1f-01c1-5a54-97f6-aeff54dada73', 'Skirt L', '{"chest_cm":[96.5,104.1],"waist_cm":[80,87.6],"hip_cm":[104.1,111.8]}'),
  ('2745f2bf-41e2-541d-9d23-c9720cc11d74', '67ba9a1f-01c1-5a54-97f6-aeff54dada73', 'Skirt XL', '{"chest_cm":[104.1,113],"waist_cm":[87.6,97.8],"hip_cm":[111.8,119.4]}'),
  ('6a8c5603-d038-5ff7-acfc-b5980aa761ea', '67ba9a1f-01c1-5a54-97f6-aeff54dada73', 'Skirt XXL', '{"chest_cm":[113,123.2],"waist_cm":[97.8,108],"hip_cm":[119.4,127]}'),
  ('04e7088c-13ed-56db-9bfd-4ea11a9c51f1', '67ba9a1f-01c1-5a54-97f6-aeff54dada73', 'Skirt 0X', '{"chest_cm":[111.8,119.4],"waist_cm":[101.6,109.2],"hip_cm":[121.9,129.5]}'),
  ('517d3d92-84cb-5311-bfa9-9d450d7fb059', '67ba9a1f-01c1-5a54-97f6-aeff54dada73', 'Skirt 1X', '{"chest_cm":[119.4,125.7],"waist_cm":[109.2,115.6],"hip_cm":[129.5,137.2]}'),
  ('4c66ddff-5222-5954-a47f-9673f5894c52', '67ba9a1f-01c1-5a54-97f6-aeff54dada73', 'Skirt 2X', '{"chest_cm":[125.7,132.1],"waist_cm":[115.6,124.5],"hip_cm":[137.2,144.8]}'),
  ('26a99d1d-18c8-5430-876e-059734a454ed', '67ba9a1f-01c1-5a54-97f6-aeff54dada73', 'Skirt 3X', '{"chest_cm":[132.1,139.7],"waist_cm":[124.5,134.6],"hip_cm":[144.8,154.9]}'),
  ('690c4449-e287-5b2e-b3f9-f522c5569d56', '67ba9a1f-01c1-5a54-97f6-aeff54dada73', 'Skirt 4X', '{"chest_cm":[139.7,147.3],"waist_cm":[134.6,144.8],"hip_cm":[154.9,165.1]}'),
  ('74505239-b91b-56ac-bd9b-9437601b7645', '67ba9a1f-01c1-5a54-97f6-aeff54dada73', 'Swim XS', '{"chest_cm":[80,85.1],"waist_cm":[61,66],"hip_cm":[87.6,92.7]}'),
  ('ac026000-6038-5d92-b8c6-8087eefd40bd', '67ba9a1f-01c1-5a54-97f6-aeff54dada73', 'Swim S', '{"chest_cm":[85.1,90.2],"waist_cm":[66,71.1],"hip_cm":[92.7,97.8]}'),
  ('6da13adc-c8bc-515a-9b2d-541fd91595c5', '67ba9a1f-01c1-5a54-97f6-aeff54dada73', 'Swim M', '{"chest_cm":[90.2,95.3],"waist_cm":[71.1,76.2],"hip_cm":[97.8,102.9]}'),
  ('f7dc4860-89c6-5371-991f-256ab0730fe6', '67ba9a1f-01c1-5a54-97f6-aeff54dada73', 'Swim L', '{"chest_cm":[95.3,102.9],"waist_cm":[76.2,83.8],"hip_cm":[102.9,110.5]}'),
  ('a3cc31ff-454f-5c8a-b49a-cdb668dc938f', '67ba9a1f-01c1-5a54-97f6-aeff54dada73', 'Swim XL', '{"chest_cm":[102.9,110.5],"waist_cm":[83.8,91.4],"hip_cm":[110.5,118.1]}'),
  ('cf7ddf12-a9c1-56dc-989e-9633072698bb', '67ba9a1f-01c1-5a54-97f6-aeff54dada73', 'Swim 2XL', '{"chest_cm":[110.5,118.1],"waist_cm":[91.4,99.1],"hip_cm":[118.1,125.7]}'),
  ('0da8f8f7-b223-5f8c-b23d-51ee03173c0c', '67ba9a1f-01c1-5a54-97f6-aeff54dada73', 'Swim 1X', '{"chest_cm":[111.8,121.9],"waist_cm":[96.5,106.7],"hip_cm":[119.4,129.5]}'),
  ('87970a29-3736-5863-961a-7d643c855f3e', '67ba9a1f-01c1-5a54-97f6-aeff54dada73', 'Swim 2X', '{"chest_cm":[121.9,132.1],"waist_cm":[106.7,116.8],"hip_cm":[129.5,139.7]}'),
  ('5c042d1a-5d4c-51a7-a959-7b2f26e7cd95', '67ba9a1f-01c1-5a54-97f6-aeff54dada73', 'Swim 3X', '{"chest_cm":[132.1,142.2],"waist_cm":[116.8,127],"hip_cm":[139.7,149.9]}')
ON CONFLICT (size_chart_id, size_label) DO UPDATE SET
  measurement_ranges = EXCLUDED.measurement_ranges,
  updated_at = now();

-- ── unisex / shoes ──

INSERT INTO brand_size_charts (id, brand_id, gender_category, product_category)
VALUES ('d0e543fc-d38e-5150-8ea8-46d03654bd39', '19abb8da-e2b5-57ab-ae0d-a4c85460bdbc', 'unisex', 'shoes')
ON CONFLICT (brand_id, gender_category, product_category) DO NOTHING;

INSERT INTO brand_size_chart_entries (id, size_chart_id, size_label, measurement_ranges)
VALUES
  ('59f4e67a-dc95-50db-990f-ac96e987f775', 'd0e543fc-d38e-5150-8ea8-46d03654bd39', 'US M3.5', '{"foot_length_cm":[22.5,22.5]}'),
  ('5fb24d34-abb2-5b30-99f9-d838596d076c', 'd0e543fc-d38e-5150-8ea8-46d03654bd39', 'US M4', '{"foot_length_cm":[23,23]}'),
  ('3ee7b64c-0751-59f1-8cfd-08bb5d895eb1', 'd0e543fc-d38e-5150-8ea8-46d03654bd39', 'US M4.5', '{"foot_length_cm":[23.5,23.5]}'),
  ('f30ad2ab-10a7-5c16-9bea-02be27abe842', 'd0e543fc-d38e-5150-8ea8-46d03654bd39', 'US M5', '{"foot_length_cm":[23.5,23.5]}'),
  ('54fa5102-cb1b-5397-bbdf-d3f1a8529f3b', 'd0e543fc-d38e-5150-8ea8-46d03654bd39', 'US M5.5', '{"foot_length_cm":[24,24]}'),
  ('91f43850-80ac-5578-8cce-82f54064e183', 'd0e543fc-d38e-5150-8ea8-46d03654bd39', 'US M6', '{"foot_length_cm":[24,24]}'),
  ('cfcc54f7-3dcb-58e0-b8c4-7597de7c708d', 'd0e543fc-d38e-5150-8ea8-46d03654bd39', 'US M6.5', '{"foot_length_cm":[24.5,24.5]}'),
  ('71072938-04c2-5697-8f1b-a60288802c2a', 'd0e543fc-d38e-5150-8ea8-46d03654bd39', 'US M7', '{"foot_length_cm":[25,25]}'),
  ('dcc90f8c-97bf-5c96-97bd-439bca70ef41', 'd0e543fc-d38e-5150-8ea8-46d03654bd39', 'US M7.5', '{"foot_length_cm":[25.5,25.5]}'),
  ('619046f7-33fe-542d-ae66-af8927e85d14', 'd0e543fc-d38e-5150-8ea8-46d03654bd39', 'US M8', '{"foot_length_cm":[26,26]}'),
  ('28efe6e5-028a-5229-8fa1-ef3b002386c1', 'd0e543fc-d38e-5150-8ea8-46d03654bd39', 'US M8.5', '{"foot_length_cm":[26.5,26.5]}'),
  ('6147b0a5-4eae-5a19-8de2-53e28f9c7120', 'd0e543fc-d38e-5150-8ea8-46d03654bd39', 'US M9', '{"foot_length_cm":[27,27]}'),
  ('7176c84c-8803-5968-baec-7b85f9ff3ba2', 'd0e543fc-d38e-5150-8ea8-46d03654bd39', 'US M9.5', '{"foot_length_cm":[27.5,27.5]}'),
  ('d910b3a2-5e31-5cd1-95e5-fb08f55bbfd2', 'd0e543fc-d38e-5150-8ea8-46d03654bd39', 'US M10', '{"foot_length_cm":[28,28]}'),
  ('b551dac1-05bd-5ac5-82cc-ee5da77a5145', 'd0e543fc-d38e-5150-8ea8-46d03654bd39', 'US M10.5', '{"foot_length_cm":[28.5,28.5]}'),
  ('0ee5ff19-190e-583b-a804-f5018b9d02b8', 'd0e543fc-d38e-5150-8ea8-46d03654bd39', 'US M11', '{"foot_length_cm":[29,29]}'),
  ('551e2d08-4bd5-5c35-9870-d61a1a9efa20', 'd0e543fc-d38e-5150-8ea8-46d03654bd39', 'US M11.5', '{"foot_length_cm":[29.5,29.5]}'),
  ('61ca6410-e2c9-5e2f-9483-aa102d0b42be', 'd0e543fc-d38e-5150-8ea8-46d03654bd39', 'US M12', '{"foot_length_cm":[30,30]}'),
  ('d5f1c4f4-9a23-5646-8e61-1767be90b5a1', 'd0e543fc-d38e-5150-8ea8-46d03654bd39', 'US M12.5', '{"foot_length_cm":[30.5,30.5]}'),
  ('cd7c2fba-2c2c-5efd-8c98-bad676b4fc1a', 'd0e543fc-d38e-5150-8ea8-46d03654bd39', 'US M13', '{"foot_length_cm":[31,31]}'),
  ('e240a38b-7867-539c-a4da-86f6b0f7be41', 'd0e543fc-d38e-5150-8ea8-46d03654bd39', 'US M13.5', '{"foot_length_cm":[31.5,31.5]}'),
  ('32f4342a-ab1a-5789-ab54-36e7c1245ff3', 'd0e543fc-d38e-5150-8ea8-46d03654bd39', 'US M14', '{"foot_length_cm":[32,32]}'),
  ('95267092-89e8-5ebb-85de-f9bd0ad3fd1f', 'd0e543fc-d38e-5150-8ea8-46d03654bd39', 'US M14.5', '{"foot_length_cm":[32.5,32.5]}'),
  ('e3672647-0c58-538a-b0f9-a2c309044855', 'd0e543fc-d38e-5150-8ea8-46d03654bd39', 'US M15', '{"foot_length_cm":[33,33]}'),
  ('c1cf56a2-0be7-55b0-af20-5833c70c1ca0', 'd0e543fc-d38e-5150-8ea8-46d03654bd39', 'US M15.5', '{"foot_length_cm":[33.5,33.5]}'),
  ('373632d9-5b8d-5271-8a88-d0ee29005fb7', 'd0e543fc-d38e-5150-8ea8-46d03654bd39', 'US M16', '{"foot_length_cm":[34,34]}'),
  ('24fb8b07-c6c5-5def-a87e-1fabfe866b8a', 'd0e543fc-d38e-5150-8ea8-46d03654bd39', 'US M16.5', '{"foot_length_cm":[34.5,34.5]}'),
  ('0d5301bf-96cf-5af7-965c-36dbf960e0ac', 'd0e543fc-d38e-5150-8ea8-46d03654bd39', 'US M17', '{"foot_length_cm":[35,35]}'),
  ('b4341eb9-ac72-52f9-94a5-b5fdd4070cd8', 'd0e543fc-d38e-5150-8ea8-46d03654bd39', 'US M17.5', '{"foot_length_cm":[35.5,35.5]}'),
  ('44de1122-1695-5aff-acab-7c4d549f5ca1', 'd0e543fc-d38e-5150-8ea8-46d03654bd39', 'US M18', '{"foot_length_cm":[36,36]}'),
  ('bff1d1d1-ce39-568b-8ee0-b1b4de464ed9', 'd0e543fc-d38e-5150-8ea8-46d03654bd39', 'US M18.5', '{"foot_length_cm":[36.5,36.5]}'),
  ('77b9b311-940c-5d08-a44e-bea3a6e1f5e4', 'd0e543fc-d38e-5150-8ea8-46d03654bd39', 'US M19', '{"foot_length_cm":[37,37]}'),
  ('c33188f9-37d6-5ccd-bc45-7af20c2667ec', 'd0e543fc-d38e-5150-8ea8-46d03654bd39', 'US M19.5', '{"foot_length_cm":[37.5,37.5]}'),
  ('55683387-252a-56a5-9213-3df5529e1650', 'd0e543fc-d38e-5150-8ea8-46d03654bd39', 'US M20', '{"foot_length_cm":[38,38]}'),
  ('46098070-62ef-5783-bb4e-34311f6bc72a', 'd0e543fc-d38e-5150-8ea8-46d03654bd39', 'US M20.5', '{"foot_length_cm":[38.5,38.5]}'),
  ('aaf03d7f-1c23-5b7d-b563-e661af241fb4', 'd0e543fc-d38e-5150-8ea8-46d03654bd39', 'US M21', '{"foot_length_cm":[39,39]}'),
  ('4d7a1571-5b07-558a-af98-38be098d6756', 'd0e543fc-d38e-5150-8ea8-46d03654bd39', 'US M21.5', '{"foot_length_cm":[39.5,39.5]}'),
  ('cd497b47-847b-5201-a378-ef37306651e1', 'd0e543fc-d38e-5150-8ea8-46d03654bd39', 'US M22', '{"foot_length_cm":[40,40]}')
ON CONFLICT (size_chart_id, size_label) DO UPDATE SET
  measurement_ranges = EXCLUDED.measurement_ranges,
  updated_at = now();

-- ── unisex / tops ──

INSERT INTO brand_size_charts (id, brand_id, gender_category, product_category)
VALUES ('ab3394f6-95ce-5cb5-b468-9f5d8860c492', '19abb8da-e2b5-57ab-ae0d-a4c85460bdbc', 'unisex', 'tops')
ON CONFLICT (brand_id, gender_category, product_category) DO NOTHING;

INSERT INTO brand_size_chart_entries (id, size_chart_id, size_label, measurement_ranges)
VALUES
  ('9b61026a-d7eb-5beb-82f6-2239a708d5da', 'ab3394f6-95ce-5cb5-b468-9f5d8860c492', 'XXS', '{"chest_cm":[72.4,80],"waist_cm":[57.2,64.8],"hip_cm":[72.4,80]}'),
  ('7127aeaa-f2e8-5cbd-8807-d54c9f591508', 'ab3394f6-95ce-5cb5-b468-9f5d8860c492', 'XS', '{"chest_cm":[80,88.9],"waist_cm":[64.8,73.7],"hip_cm":[80,88.9]}'),
  ('0b48a4c1-f505-5fbd-9b9d-1157622cb7ef', 'ab3394f6-95ce-5cb5-b468-9f5d8860c492', 'S', '{"chest_cm":[88.9,95.3],"waist_cm":[73.7,81.3],"hip_cm":[88.9,95.3]}'),
  ('cb399865-ebe4-5822-b37c-fcfa92241832', 'ab3394f6-95ce-5cb5-b468-9f5d8860c492', 'S Tall', '{"chest_cm":[88.9,95.3],"waist_cm":[73.7,81.3],"hip_cm":[88.9,95.3]}'),
  ('09dd2ee2-3947-52f1-b6a7-1501d44fbbe2', 'ab3394f6-95ce-5cb5-b468-9f5d8860c492', 'M', '{"chest_cm":[95.3,104.1],"waist_cm":[81.3,88.9],"hip_cm":[95.3,104.1]}'),
  ('a5e62c90-239a-53fe-bb90-8f6503e0b32c', 'ab3394f6-95ce-5cb5-b468-9f5d8860c492', 'M Tall', '{"chest_cm":[95.3,104.1],"waist_cm":[81.3,88.9],"hip_cm":[95.3,104.1]}'),
  ('f420eeaf-f3c6-5586-a5c4-06fc45fe5573', 'ab3394f6-95ce-5cb5-b468-9f5d8860c492', 'L', '{"chest_cm":[104.1,111.8],"waist_cm":[88.9,96.5],"hip_cm":[104.1,111.8]}'),
  ('7a682f73-cf0e-5a14-a411-d2825f110c90', 'ab3394f6-95ce-5cb5-b468-9f5d8860c492', 'L Tall', '{"chest_cm":[104.1,111.8],"waist_cm":[88.9,96.5],"hip_cm":[104.1,111.8]}'),
  ('cb789dcd-d41b-5107-92af-0fd3102e421c', 'ab3394f6-95ce-5cb5-b468-9f5d8860c492', 'XL', '{"chest_cm":[111.8,123.2],"waist_cm":[96.5,109.2],"hip_cm":[111.8,119.4]}'),
  ('0b7a165a-5c74-5756-9f58-dcfcebfda06e', 'ab3394f6-95ce-5cb5-b468-9f5d8860c492', 'XL Tall', '{"chest_cm":[111.8,123.2],"waist_cm":[96.5,109.2],"hip_cm":[111.8,119.4]}'),
  ('f1ed3050-5d85-59c2-8060-a59025e8ac4c', 'ab3394f6-95ce-5cb5-b468-9f5d8860c492', 'XXL', '{"chest_cm":[123.2,135.9],"waist_cm":[109.2,120.7],"hip_cm":[119.4,128.3]}'),
  ('0b7328e7-65dd-5a3c-a923-0c8641e35bf4', 'ab3394f6-95ce-5cb5-b468-9f5d8860c492', 'XXL Tall', '{"chest_cm":[123.2,135.9],"waist_cm":[109.2,120.7],"hip_cm":[119.4,128.3]}'),
  ('1f0b2655-48c6-571f-b69d-30f56699fe7f', 'ab3394f6-95ce-5cb5-b468-9f5d8860c492', '3XL', '{"chest_cm":[135.9,147.3],"waist_cm":[120.7,133.4],"hip_cm":[128.3,135.9]}'),
  ('3061b711-e0b6-5d45-9bb3-d6380a4476d5', 'ab3394f6-95ce-5cb5-b468-9f5d8860c492', '3XL Tall', '{"chest_cm":[135.9,147.3],"waist_cm":[120.7,133.4],"hip_cm":[128.3,135.9]}'),
  ('c096685d-8bf9-5340-9276-b252ef37618f', 'ab3394f6-95ce-5cb5-b468-9f5d8860c492', '4XL', '{"chest_cm":[147.3,160],"waist_cm":[133.4,144.8],"hip_cm":[135.9,148.6]}'),
  ('8353e6a7-6080-5265-9e69-a401a796d42e', 'ab3394f6-95ce-5cb5-b468-9f5d8860c492', '4XL Tall', '{"chest_cm":[147.3,160],"waist_cm":[133.4,144.8],"hip_cm":[135.9,148.6]}')
ON CONFLICT (size_chart_id, size_label) DO UPDATE SET
  measurement_ranges = EXCLUDED.measurement_ranges,
  updated_at = now();

-- Summary: 8 charts, 291 entries
