#!/usr/bin/env tsx
/**
 * Reads nb_size_data.json and appends New Balance seed SQL to supabase/seed.sql
 */

import { readFileSync, writeFileSync, appendFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { v5 as uuidv5 } from 'uuid';

const FITR_NAMESPACE = '6ba7b810-9dad-11d1-80b4-00c04fd430c8';

function seedUuid(...parts: string[]): string {
  return uuidv5(parts.join(':'), FITR_NAMESPACE);
}

interface ParsedEntry {
  sizeLabel: string;
  measurementRanges: Record<string, [number, number]>;
}

interface SubChart {
  slug: string;
  genderCategory: string;
  productCategory: string;
  labelPrefix: string;
  storable: boolean;
  entries: ParsedEntry[];
}

interface SizeData {
  brand: { name: string; region: string; enabled: boolean };
  subCharts: SubChart[];
}

function esc(val: string): string {
  return val.replace(/'/g, "''");
}

function jsonStr(obj: unknown): string {
  return esc(JSON.stringify(obj));
}

function main() {
  const jsonPath = resolve(import.meta.dirname, '../../supabase/seed/nb_size_data.json');
  const data: SizeData = JSON.parse(readFileSync(jsonPath, 'utf-8'));

  const brandId = seedUuid('brand', data.brand.name);
  const lines: string[] = [
    '',
    '-- ══════════════════════════════════════════════════════════',
    '-- New Balance — Auto-generated by scripts/seed/generate-nb-sql.ts',
    `-- Generated at: ${new Date().toISOString()}`,
    '-- ══════════════════════════════════════════════════════════',
    '',
    `INSERT INTO brands (id, name, enabled, region)`,
    `VALUES ('${brandId}', '${esc(data.brand.name)}', ${data.brand.enabled}, '${esc(data.brand.region)}')`,
    `ON CONFLICT (name) DO UPDATE SET enabled = EXCLUDED.enabled, region = EXCLUDED.region;`,
    '',
  ];

  // Group storable sub-charts by (gender, category)
  const storableCharts = data.subCharts.filter(sc => sc.storable && sc.entries.length > 0);
  const groups = new Map<string, SubChart[]>();

  for (const sc of storableCharts) {
    const key = `${sc.genderCategory}:${sc.productCategory}`;
    if (!groups.has(key)) groups.set(key, []);
    groups.get(key)!.push(sc);
  }

  let totalEntries = 0;

  for (const [groupKey, subCharts] of groups) {
    const [gender, category] = groupKey.split(':');
    const chartId = seedUuid('chart', data.brand.name, gender, category);

    lines.push(`-- ── ${gender} / ${category} ──`);
    lines.push('');
    lines.push(`INSERT INTO brand_size_charts (id, brand_id, gender_category, product_category)`);
    lines.push(`VALUES ('${chartId}', '${brandId}', '${esc(gender)}', '${esc(category)}')`);
    lines.push(`ON CONFLICT (brand_id, gender_category, product_category) DO NOTHING;`);
    lines.push('');

    const seenLabels = new Set<string>();
    const allEntries: ParsedEntry[] = [];

    for (const sc of subCharts) {
      for (const entry of sc.entries) {
        const label = sc.labelPrefix + entry.sizeLabel;
        if (seenLabels.has(label)) {
          console.warn(`  ⚠ Duplicate label "${label}" in ${gender}/${category} — skipping`);
          continue;
        }
        seenLabels.add(label);
        allEntries.push({ ...entry, sizeLabel: label });
      }
    }

    if (allEntries.length === 0) continue;

    lines.push(`INSERT INTO brand_size_chart_entries (id, size_chart_id, size_label, measurement_ranges)`);
    lines.push('VALUES');

    const valueLines: string[] = [];
    for (const entry of allEntries) {
      const entryId = seedUuid('entry', data.brand.name, gender, category, entry.sizeLabel);
      valueLines.push(
        `  ('${entryId}', '${chartId}', '${esc(entry.sizeLabel)}', '${jsonStr(entry.measurementRanges)}')`
      );
    }

    lines.push(valueLines.join(',\n'));
    lines.push('ON CONFLICT (size_chart_id, size_label) DO UPDATE SET');
    lines.push('  measurement_ranges = EXCLUDED.measurement_ranges,');
    lines.push('  updated_at = now();');
    lines.push('');

    totalEntries += allEntries.length;
  }

  lines.push(`-- Summary: ${groups.size} charts, ${totalEntries} entries`);

  // Append to existing seed.sql
  const sqlPath = resolve(import.meta.dirname, '../../supabase/seed.sql');
  appendFileSync(sqlPath, lines.join('\n') + '\n', 'utf-8');
  console.log(`Appended to ${sqlPath}`);
  console.log(`  ${groups.size} parent charts, ${totalEntries} entries`);
}

main();
