#!/usr/bin/env tsx
/**
 * Reads nike_size_data.json and generates supabase/seed.sql
 * with idempotent INSERT statements for the brand, size charts, and entries.
 *
 * Uses deterministic UUIDv5 so the seed is repeatable.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { v5 as uuidv5 } from 'uuid';

// ── Deterministic UUID namespace for Fitr seed data ─────────

const FITR_NAMESPACE = '6ba7b810-9dad-11d1-80b4-00c04fd430c8'; // DNS namespace as base

function seedUuid(...parts: string[]): string {
  return uuidv5(parts.join(':'), FITR_NAMESPACE);
}

// ── Types matching the scraper output ───────────────────────

interface ParsedEntry {
  sizeLabel: string;
  measurementRanges: Record<string, [number, number]>;
}

interface NikeSubChart {
  slug: string;
  genderCategory: string;
  productCategory: string;
  labelPrefix: string;
  storable: boolean;
  entries: ParsedEntry[];
  warnings: string[];
}

interface NikeSizeData {
  brand: { name: string; region: string; enabled: boolean };
  subCharts: NikeSubChart[];
}

// ── SQL escaping ────────────────────────────────────────────

function esc(val: string): string {
  return val.replace(/'/g, "''");
}

function jsonStr(obj: unknown): string {
  return esc(JSON.stringify(obj));
}

// ── Main ────────────────────────────────────────────────────

function main() {
  const jsonPath = resolve(import.meta.dirname, '../../supabase/seed/nike_size_data.json');
  const data: NikeSizeData = JSON.parse(readFileSync(jsonPath, 'utf-8'));

  const brandId = seedUuid('brand', data.brand.name);
  const lines: string[] = [
    '-- Auto-generated by scripts/seed/generate-sql.ts',
    '-- Do not edit manually. Re-run the generator after scraping.',
    `-- Generated at: ${new Date().toISOString()}`,
    '',
    '-- ── Nike brand ──────────────────────────────────────────',
    '',
    `INSERT INTO brands (id, name, enabled, region)`,
    `VALUES ('${brandId}', '${esc(data.brand.name)}', ${data.brand.enabled}, '${esc(data.brand.region)}')`,
    `ON CONFLICT (name) DO UPDATE SET enabled = EXCLUDED.enabled, region = EXCLUDED.region;`,
    '',
  ];

  // Group storable sub-charts by (gender, category)
  const storableCharts = data.subCharts.filter(sc => sc.storable && sc.entries.length > 0);
  const groups = new Map<string, NikeSubChart[]>();

  for (const sc of storableCharts) {
    const key = `${sc.genderCategory}:${sc.productCategory}`;
    if (!groups.has(key)) groups.set(key, []);
    groups.get(key)!.push(sc);
  }

  for (const [groupKey, subCharts] of groups) {
    const [gender, category] = groupKey.split(':');
    const chartId = seedUuid('chart', data.brand.name, gender, category);

    lines.push(`-- ── ${gender} / ${category} ──`);
    lines.push('');
    lines.push(`INSERT INTO brand_size_charts (id, brand_id, gender_category, product_category)`);
    lines.push(`VALUES ('${chartId}', '${brandId}', '${esc(gender)}', '${esc(category)}')`);
    lines.push(`ON CONFLICT (brand_id, gender_category, product_category) DO NOTHING;`);
    lines.push('');

    // Merge all entries from sub-charts in this group
    // Check for label conflicts
    const seenLabels = new Set<string>();
    const allEntries: ParsedEntry[] = [];

    for (const sc of subCharts) {
      for (const entry of sc.entries) {
        if (seenLabels.has(entry.sizeLabel)) {
          console.warn(`  ⚠ Duplicate label "${entry.sizeLabel}" in ${gender}/${category} from ${sc.slug} — skipping`);
          continue;
        }
        seenLabels.add(entry.sizeLabel);
        allEntries.push(entry);
      }
    }

    if (allEntries.length === 0) continue;

    lines.push(`INSERT INTO brand_size_chart_entries (id, size_chart_id, size_label, measurement_ranges)`);
    lines.push('VALUES');

    const valueLines: string[] = [];
    for (const entry of allEntries) {
      const entryId = seedUuid('entry', data.brand.name, gender, category, entry.sizeLabel);
      valueLines.push(
        `  ('${entryId}', '${chartId}', '${esc(entry.sizeLabel)}', '${jsonStr(entry.measurementRanges)}')`
      );
    }

    lines.push(valueLines.join(',\n'));
    lines.push('ON CONFLICT (size_chart_id, size_label) DO UPDATE SET');
    lines.push('  measurement_ranges = EXCLUDED.measurement_ranges,');
    lines.push('  updated_at = now();');
    lines.push('');
  }

  // Summary comment
  const totalCharts = groups.size;
  const totalEntries = [...groups.values()].reduce(
    (sum, scs) => sum + scs.reduce((s, sc) => s + sc.entries.length, 0),
    0,
  );
  lines.push(`-- Summary: ${totalCharts} charts, ${totalEntries} entries`);

  const sqlPath = resolve(import.meta.dirname, '../../supabase/seed.sql');
  writeFileSync(sqlPath, lines.join('\n') + '\n', 'utf-8');
  console.log(`Wrote ${sqlPath}`);
  console.log(`  ${totalCharts} parent charts, ${totalEntries} entries`);
}

main();
